version: "3.8"

services:
  rails-app:
    build: .
    container_name: rails-app
    working_dir: /app
    command: bash -c "bundle exec rails server -b 0.0.0.0 -p 3000"
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
    ports:
      - "3000:3000"
    labels:
      com.datadoghq.ad.logs: '[{"service":"rails-app","source":"ruby"}]'
    depends_on:
      - datadog-agent

  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"
      - DD_SITE=datadoghq.eu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
